updated and improved tmanin_hybrid script

diff --git a/tmanin_hybrid b/tmanin_hybrid
--- a/tmanin_hybrid
+++ b/tmanin_hybrid
@@ -5,19 +5,21 @@ N=$2
 NAP=100
 VERBOSE=0
 
-ln -s tmanin_loop_long tmanin_l_$d$_$N
+PARAMS="${d} ${VERBOSE} 1 ${NAP} 1 1 ${N} ${N}"
 
-echo $d ${VERBOSE} 1 ${NAP} 1 1 $N $N | ./tmanin_l_$d$_$N
+PROG="./tmanin_l_${d}_${N}"
+ln -s tmanin_loop_long "${PROG}"
 
-if [ $? -eq 0 ]
+if ! (echo "${PARAMS}" | "${PROG}");
 then
-  echo "tmanin (d=$d, N=$N) using long ints succeeded"
-  /bin/rm tmanin_l_$d$_$N
+  echo "${PROG} using long ints succeeded"
+  /bin/rm "${PROG}"
 else
-  echo "******************** tmanin (d=$d, N=$N) using long ints FAILED, rerunning with ZZ *******************************"
-  ln -s tmanin_loop_ZZ tmanin_ZZ_$d$_$N
-  echo $d ${VERBOSE} 1 ${NAP} 1 1 $N $N | ./tmanin_ZZ_$d$_$N
-  /bin/rm tmanin_ZZ_$d$_$N
+  echo "******************** ${PROG} using long ints FAILED, rerunning with ZZ *******************************"
+  /bin/rm "${PROG}"
+  PROG="./tmanin_ZZ_${d}_${N}"
+  ln -s tmanin_loop_ZZ "${PROG}"
+  echo "${PARAMS}" | "${PROG}"
 fi
 
 # To use in parallel runs, one level norm per run:
